blank_issues_enabled: false
contact_links:
  - name: Stellar Developer Discord
    url: https://discord.gg/stellardev
    about: Ask questions and get help from the Stellar community
  - name: Stellar Documentation
    url: https://developers.stellar.org
    about: Official Stellar developer documentation
